channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.2.2
  - torchvision
  - torchaudio
  - numpy=1.24.3
  - matplotlib
  - gymnasium=0.28.1
  - cloudpickle
  - tqdm
  - swig
  - scipy
  - pandas
  - seaborn
  - scikit-learn
  - pip
  - pip:
      - box2d-py==2.3.5
      - gym==0.26.2
      - pygame==2.1.3
      - moviepy==1.0.3
      - requests
      - beautifulsoup4
      - flask